### ISSUE TITLE
Command argument is not typed correctly

### ISSUE THREAD

**Issue by kawinie** [hongaar/bandersnatch#388]
Hi there,

Argument type inferred from `argument()` is optional by default. As an example, in the below code, `count` is inferred as `number | undefined`. Shouldn't this be `number` since there is also `optional` option as well?

```ts
command("step", { description: "Tells the stepper motor to turn X steps" })
    .argument("count", {
        type: "number",
        description: "Number of steps to turn",
        prompt: "Enter the number of steps",
    })
    .option("delay_ms", { type: "number" })
    .action(async ({ count, delay_ms }) => await step(count, delay_ms));
```

**Comment by hongaar** [comment]
Hi @kawinie, thanks for reporting this. It should be fixed in the latest release. Let me know if you still encounter problems with the argument types. I intend to do some further work to force argument types in the future (e.g. it's now possible to declare/type an argument as 'number' but still get back a 'string' runtime type).
